<template>
    <nav class="flex justify-center">
        <div
        :class="[
            'navContainer',
            'z-100',
            'bg-backgroundsecond/50',
            'backdrop-blur-xl',
            'fixed',
            'bottom-[10px]',
            'min-h-[64px]',
            'sm:min-h-[128px]',
            'flex',
            'items-center',
            'justify-center',
            'gap-4',
            'rounded-[26px]',
            'p-[14px]',
            'ring-2',
            'ring-neutral-500/10',
            'shadow-xl',
            'shadow-shadow/15',
        ]"
        >
            <slot/>
        </div>
    </nav>
</template>
